### ISSUE TITLE
Video Viewed from only the Device on which Relay Server Runs.

### ISSUE THREAD

**Issue by shivbuyya** [ReferenceType/P2PVideocall#1]
Hi,

It is very good application for peer to peer video call. I am facing some issues as explained below.

I am running **Relay Server on 192.168.1.35**, Also running one client application on the same device with username **Test1**.
I am running client application on 2 more devices with usernames **Test2 and Test3**. In these devices application setting host IP is provided as 192.168.1.35. So I am able to see Online peers.

Case1: When I call from Test1 to Test2, video is shown on Test2, but there is no video and audio incoming on Test1.
Case2: Call between Test2 and Test3, no video seen on both devices.

So my observation is Video is transferred from only device with username Test1, where the Relay server is running.

Please let me know what is the issue?

Is it possible to have communication between end devices without having Relay server?

**Comment by ReferenceType** [comment]
Thanks for the comment and raising this issue.
Strange, I have tested this app on my work environment with my colleagues with Lan \ WIFI in similar setup.

I have few questions:
- Do you have device permissions to access camera and video?
- Do you use holepunch feature?
- What's the resolutions of your cameras? (is it very high resolution?)

Can you also try this and get back to me, it helps me identify the issue
- Change the transport layer to TCP and see if the call works
- Send a small file between peers to see if it transfers.

I will investigate it, btw there will be huge patch on the network side soon.

**Comment by shivbuyya** [comment]
Thanks for the response.

- Do you have device permissions to access camera and video?
        **Yes**
- Do you use holepunch feature?
        **I have enabled checkbox Auto HolePunch from Settings.**
- What's the resolutions of your cameras? (is it very high resolution?)
       ****I am using Getac T800 Rugged Tablet** it has 8MP Camera resolution.** I have also tried to connect external camera Logitech HD 720p. could not succeed, **as there is no option to switch the camera**.

As you suggested :

-  I have tried to establish call by changing the transport layer to TCP from the settings. But still video is not shown from Getac T800.
- Tested File transfer, it is working fine.

Also can you clarify which codec is used for video call? Because in settings it shows webp and jpg.

For low bandwidth can we use VP8 or H.264 in this app?

**Comment by ReferenceType** [comment]
So problem seems to be not on network but on acquisition of devices.
I am assuming you are using a pre-built version from one of the releases (i.e. v0.2.0-alpha) so we dont have version incompatibility. 

I'm using Open CV wrapper for getting the device camera, and NAudio for the audio. Both takes the default device they can find. You pointed that there is no audio and video, so both of them is failing.

To verify this, you can check it by calling from a device which the cam feed doesn't work,  you will see yourself on right top corner Inside the application. If it doesn't show anything or shows a black rectangle, means camera is not acquired. For audio similarly there is an option in setting "listen yourself" works when you are on call.

My suspicion is that what you are using is a windows tablet, I never used or tested on windows tablets, only on home Pcs and some thinkpad laptops. Maybe they have more security to determine which app can access to device.  I assume the one that works is not a tablet? Have you tired to run as admin?

About H.264, I intend to implement it, on C# there is no direct implementation or readily available library. I probably need to do a wrapper around Cisco's H.264 encoder(C++).  However there is no documentation so it will take a bit of time.
So current codec is  is stream of Jpg images or WebP(smaller size) images. You can call it MJpeg I guess. They take about 200-400 Kb/s on my device. You can also reduce or bump the quality or fps manually with a slider.
Bare in mind this app is a toy app i did on few weekends, mainly to test my network library. So unfortunately, it not feature rich yet.

**Comment by ReferenceType** [comment]
Forgot to ask you, have you tried share screen? Does it work?

**Comment by shivbuyya** [comment]
Hi, 

Share screen is working fine, also I have checked self view of video is shown in the Getac Tablet. Randomly sometimes video also transmitted successfully, when I had run app as admin. But it won't work on everytime call initiated from either side. Success rate is very less. Not sure why it behaves so?

**Comment by ReferenceType** [comment]
Thanks for your tests and responses.
I think I have an idea on your last issue where images are transmitted "sometimes".

After image is acquired from camera, its compressed to either Jpg or WebP. If the compressed image is more than 64Kb, it will be dropped because it cant fit on single UDP datagram. 

Normally when you enable "Congestion Control" on video settings it should automatically drop the quality. Or you can disable it and manually drop the quality. 

Another reason could be that, the WebP is computationally intensive image compression. Maybe the tablet CPU is not powerful enough to handle it on real-time. So you can try to switch on JPG. Share screen also uses WebP compression. So maybe that's not it on your case.

In any case I will patch the points you raised on future release soon. 
Cheers

**Comment by shivbuyya** [comment]
OK thank you so much for the responses. Lets hope you will be able to the patch all the points.

**Comment by ReferenceType** [comment]
If you have time, just to confirm the theory, can you try it by switching to JPG and reducing the quality manually (disable the congestion control, lower the slider), to see if it transmits on lower qualities? you can also try the transport layer at TCP to see if it makes any difference.
Thanks

**Comment by ReferenceType** [comment]
Ok, 
I implemented H264 encoding and Jumbo Udp frame support for large udp messages.  There is now also camera selection and test options on settings section for multi-camera setups. You can check the new version on latest release.
This should resolve the issue.
Note that if your tablet is based on ARM processor, application is not supported yet.
Closing this issue, if new one arises, don't hesitate to create one.
